name: 'GitHub Merge Lock (Status)'
description: 'Check lock status via repository rulesets'
author: 'papix'

inputs:
  github_token:
    description: 'GitHub token with repository administration permissions'
    required: true
  owner:
    description: 'Repository owner (defaults to current repository owner)'
    required: false
    default: ''
  repo:
    description: 'Repository name (defaults to current repository name)'
    required: false
    default: ''
  branch:
    description: 'Branch name to check'
    required: true
  ruleset_name:
    description: 'Ruleset name (default: github-merge-lock:<branch>)'
    required: false
    default: ''

outputs:
  locked:
    description: 'Lock status'
    value: ${{ steps.status.outputs.locked }}
  ruleset_id:
    description: 'Ruleset ID'
    value: ${{ steps.status.outputs.ruleset_id }}
  enforcement:
    description: 'Ruleset enforcement'
    value: ${{ steps.status.outputs.enforcement }}
  found:
    description: 'Whether the ruleset exists'
    value: ${{ steps.status.outputs.found }}
  ruleset_name:
    description: 'Resolved ruleset name'
    value: ${{ steps.status.outputs.ruleset_name }}

runs:
  using: 'composite'
  steps:
    - name: Check branch status
      id: status
      shell: bash
      working-directory: ${{ github.action_path }}/../..
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_OWNER: ${{ inputs.owner }}
        INPUT_REPO: ${{ inputs.repo }}
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_RULESET_NAME: ${{ inputs.ruleset_name }}
      run: pnpm exec tsx ${{ github.action_path }}/src/index.ts
